Repository vuejs-jp/handson-vue3, pull requests merged in 2021-09, with the labels that each got.

#60 refactor: scoped styleを削除する
  docs/event.md
  docs/overview.md
  examples/event/src/App.vue
  examples/overview/src/components/HelloWorld.vue
  src/App.vue
Labels: documentation, example

#67 VuePress を GitHub Pages に自動デプロイするワークフローの実装
  .github/workflows/vuepress.yml
  docs/.gitignore
  docs/.vuepress/config.js
  docs/create.md
  docs/overview.md
  docs/v-for.md
Labels: documentation

#66 VS Code の略称を修正
  docs/setup.md
Labels: bug, documentation

#72 fix: methods へのリンクを修正
  docs/README.md
  docs/overview.md
Labels: bug, documentation

#73 `v-for` と `v-if` のガイド内のタグを修正
  docs/v-for.md
  docs/v-if.md
Labels: bug, documentation

#71 docs: Vue CLI を 4.5.13 に変更した手順に変更
  docs/create.md
Labels: documentation

#95 GitHub Pages でカスタムドメインを利用する
  docs/.vuepress/config.js
Labels: documentation

#93 v-forでループするときにtemplateを利用する
  docs/event.md
  docs/overview.md
  examples/event/src/App.vue
  examples/methods/src/App.vue
  examples/v-for/src/App.vue
  examples/v-if/src/App.vue
  src/App.vue
Labels: documentation, example

#97 fix: VuePress のカスタムドメイン対応
  .github/workflows/vuepress.yml
Labels: bug
