Repository vuejs-jp/handson-vue3, pull requests merged in 2022-01, with the labels that each got.

#111 ガイド追加: @click で商品を選択する
  docs/event.md
Labels: documentation, enhancement

#113 完成品サンプルへのリンクを追加
  docs/overview.md
Labels: documentation

#115 chore: formatter の設定を最適化
  .editorconfig
  .eslintrc.js
  .gitignore
  .prettierrc.js
  .vscode/settings.json
  examples/event/src/App.vue
  examples/methods/src/App.vue
  examples/overview/src/App.vue
  examples/overview/src/components/HelloWorld.vue
  examples/rendering/src/App.vue
  examples/v-for/src/App.vue
  examples/v-if/src/App.vue
  package-lock.json
  package.json
  src/App.vue
Labels: example
